#!/bin/bash
mkdir -p $HOME/.kube
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config
export kubever=$(kubectl version | base64 | tr -d '\n')
#kubectl apply -f https://github.com/weaveworks/weave-kube/releases/download/latest_release/weave-daemonset.yaml
kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$kubever"
